apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-service
  labels:
    app: node-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-service

  template:
    metadata:
      labels:
        app: node-service

    spec:
      containers:
        - name: node-service
          image: ghcr.io/noussayba98/node-service-template:f6d1e40cc958fadb79dc4be3e312f5f1864d9cd9
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
